apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-claim
  namespace: velero
  annotations:
   volume.beta.kubernetes.io/storage-class: minio-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: projectpacific-storage-policy
