apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: projectpacific-storage-policy
